In [ ]:
!pip install pandas

In [43]:
import pandas as pd

pd.set_option('display.max_rows', None)

file_path = '/content/dados.csv'
df = pd.read_csv(file_path, sep=';', engine='python', encoding='latin1')

if df.shape[1] == 1:
    df = pd.read_csv(file_path, sep=',', engine='python', encoding='latin1')

# Verifique os nomes das colunas
print("Nomes das colunas:")
print(df.columns)

# Imprima as informações gerais sobre o conjunto de dados
print("\nInformações gerais sobre o conjunto de dados:")
print(df.info())

# Imprima as primeiras e últimas N linhas do arquivo
print("\nPrimeiras linhas do arquivo:")
print(df.head(1))

print("\nÚltimas linhas do arquivo:")
print(df.tail(1))

# cópia dos dados originais
df_clean = df.copy()

# Verifique a existência da coluna 'Calories'
if 'Calories' in df_clean.columns:
    # Substitua valores 'NaN' por 0 apenas na coluna 'Calories'
    df_clean['Calories'] = df_clean['Calories'].fillna(0)
    print("\nDados após substituir valores 'NaN' na coluna 'Calories' por 0:")
    print(df_clean)

else:
    print("\nA coluna 'Calories' não foi encontrada no conjunto de dados.")

# Verifique a existência da coluna 'Date' e substitua os valores nulos por '1900/01/01'
if 'Date' in df_clean.columns:
    df_clean['Date'].fillna('1900/01/01', inplace=True)
    # Imprima o conjunto de dados para verificar a mudança
    print("\nDados após substituir valores nulos na coluna 'Date' por '1900/01/01':")
    print(df_clean)

    # Verifique o formato real dos dados na coluna 'Date'
    print("\nPrimeiras 5 datas na coluna 'Date':")
    print(df_clean['Date'].head(5))

    # Transforme os dados da coluna 'Date' em datetime
    try:
        df_clean['Date'] = pd.to_datetime(df_clean['Date'], errors='coerce')
        # Substitua '1900-01-01' por NaT
        df_clean['Date'].replace(pd.Timestamp('1900-01-01'), pd.NaT, inplace=True)
    except ValueError as e:
        print(f"\nErro ao transformar a coluna 'Date' para datetime: {e}")

    print("\nDados após transformar a coluna 'Date' para datetime:")
    print(df_clean)

else:
    print("\nA coluna 'Date' não foi encontrada no conjunto de dados.")

# Remova registros com valores nulos na coluna 'Date'
if 'Date' in df_clean.columns:
    df_clean.dropna(subset=['Date'], inplace=True)

# Imprime o dataframe e verifique se todas as transformações foram aplicadas
print("\nDados após remover registros com valores nulos na coluna 'Date':")
print(df_clean)

Nomes das colunas:
Index(['ID', 'Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

Informações gerais sobre o conjunto de dados:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        32 non-null     int64
 1   Duration  32 non-null     int64
 2   Date      31 non-null     object
 3   Pulse     32 non-null     int64
 4   Maxpulse  32 non-null     int64
 5   Calories  30 non-null     float64
dtypes: float64(1), int64(4), object(1)
memory usage: 1.6+ KB
None

Primeiras linhas do arquivo:
   ID  Duration         Date  Pulse  Maxpulse  Calories
0   0        60  2020/12/01'    110       130    4091.0

Últimas linhas do arquivo:
    ID  Duration         Date  Pulse  Maxpulse  Calories
31  31        60  2020/12/31'     92       115    2430.0

Dados após substituir valores 'NaN' na coluna 'Calories' por 0:
    ID  Duration         Date  Pulse  Maxpulse  Calories
0    0        60  2020/12/01'    110       130    4091.0
1    1        60  2020/12/02'    117       145    4790.0
2    2        60  2020/12/03'    103       135    3400.0
3    3        45  2020/12/04'    109       175    2824.0
4    4        45  2020/12/05'    117       148    4060.0
5    5        60  2020/12/06'    102       127    3000.0
6    6        60  2020/12/07'    110       136    3740.0
7    7       450  2020/12/08'    104       134    2533.0
8    8        30  2020/12/09'    109       133    1951.0
9    9        60  2020/12/10'     98       124    2690.0
10  10        60  2020/12/11'    103       147    3293.0
11  11        60  2020/12/12'    100       120    2507.0
12  12        60  2020/12/12'    100       120    2507.0
13  13        60  2020/12/13'    106       128    3453.0
14  14        60  2020/12/14'    104       132    3793.0
15  15        60  2020/12/15'     98       123    2750.0
16  16        60  2020/12/16'     98       120    2152.0
17  17        60  2020/12/17'    100       120    3000.0
18  18        45  2020/12/18'     90       112       0.0
19  19        60  2020/12/19'    103       123    3230.0
20  20        45  2020/12/20'     97       125    2430.0
21  21        60  2020/12/21'    108       131    3642.0
22  22        45          NaN    100       119    2820.0
23  23        60  2020/12/23'    130       101    3000.0
24  24        45  2020/12/24'    105       132    2460.0
25  25        60  2020/12/25'    102       126    3345.0
26  26        60    20201226'    100       120    2500.0
27  27        60  2020/12/27'     92       118    2410.0
28  28        60  2020/12/28'    103       132       0.0
29  29        60  2020/12/29'    100       132    2800.0
30  30        60  2020/12/30'    102       129    3803.0
31  31        60  2020/12/31'     92       115    2430.0

Dados após substituir valores nulos na coluna 'Date' por '1900/01/01':
    ID  Duration         Date  Pulse  Maxpulse  Calories
0    0        60  2020/12/01'    110       130    4091.0
1    1        60  2020/12/02'    117       145    4790.0
2    2        60  2020/12/03'    103       135    3400.0
3    3        45  2020/12/04'    109       175    2824.0
4    4        45  2020/12/05'    117       148    4060.0
5    5        60  2020/12/06'    102       127    3000.0
6    6        60  2020/12/07'    110       136    3740.0
7    7       450  2020/12/08'    104       134    2533.0
8    8        30  2020/12/09'    109       133    1951.0
9    9        60  2020/12/10'     98       124    2690.0
10  10        60  2020/12/11'    103       147    3293.0
11  11        60  2020/12/12'    100       120    2507.0
12  12        60  2020/12/12'    100       120    2507.0
13  13        60  2020/12/13'    106       128    3453.0
14  14        60  2020/12/14'    104       132    3793.0
15  15        60  2020/12/15'     98       123    2750.0
16  16        60  2020/12/16'     98       120    2152.0
17  17        60  2020/12/17'    100       120    3000.0
18  18        45  2020/12/18'     90       112       0.0
19  19        60  2020/12/19'    103       123    3230.0
20  20        45  2020/12/20'     97       125    2430.0
21  21        60  2020/12/21'    108       131    3642.0
22  22        45   1900/01/01    100       119    2820.0
23  23        60  2020/12/23'    130       101    3000.0
24  24        45  2020/12/24'    105       132    2460.0
25  25        60  2020/12/25'    102       126    3345.0
26  26        60    20201226'    100       120    2500.0
27  27        60  2020/12/27'     92       118    2410.0
28  28        60  2020/12/28'    103       132       0.0
29  29        60  2020/12/29'    100       132    2800.0
30  30        60  2020/12/30'    102       129    3803.0
31  31        60  2020/12/31'     92       115    2430.0

Primeiras 5 datas na coluna 'Date':
0    2020/12/01'
1    2020/12/02'
2    2020/12/03'
3    2020/12/04'
4    2020/12/05'
Name: Date, dtype: object

Dados após transformar a coluna 'Date' para datetime:
    ID  Duration       Date  Pulse  Maxpulse  Calories
0    0        60 2020-12-01    110       130    4091.0
1    1        60 2020-12-02    117       145    4790.0
2    2        60 2020-12-03    103       135    3400.0
3    3        45 2020-12-04    109       175    2824.0
4    4        45 2020-12-05    117       148    4060.0
5    5        60 2020-12-06    102       127    3000.0
6    6        60 2020-12-07    110       136    3740.0
7    7       450 2020-12-08    104       134    2533.0
8    8        30 2020-12-09    109       133    1951.0
9    9        60 2020-12-10     98       124    2690.0
10  10        60 2020-12-11    103       147    3293.0
11  11        60 2020-12-12    100       120    2507.0
12  12        60 2020-12-12    100       120    2507.0
13  13        60 2020-12-13    106       128    3453.0
14  14        60 2020-12-14    104       132    3793.0
15  15        60 2020-12-15     98       123    2750.0
16  16        60 2020-12-16     98       120    2152.0
17  17        60 2020-12-17    100       120    3000.0
18  18        45 2020-12-18     90       112       0.0
19  19        60 2020-12-19    103       123    3230.0
20  20        45 2020-12-20     97       125    2430.0
21  21        60 2020-12-21    108       131    3642.0
22  22        45        NaT    100       119    2820.0
23  23        60 2020-12-23    130       101    3000.0
24  24        45 2020-12-24    105       132    2460.0
25  25        60 2020-12-25    102       126    3345.0
26  26        60        NaT    100       120    2500.0
27  27        60 2020-12-27     92       118    2410.0
28  28        60 2020-12-28    103       132       0.0
29  29        60 2020-12-29    100       132    2800.0
30  30        60 2020-12-30    102       129    3803.0
31  31        60 2020-12-31     92       115    2430.0

Dados após remover registros com valores nulos na coluna 'Date':
    ID  Duration       Date  Pulse  Maxpulse  Calories
0    0        60 2020-12-01    110       130    4091.0
1    1        60 2020-12-02    117       145    4790.0
2    2        60 2020-12-03    103       135    3400.0
3    3        45 2020-12-04    109       175    2824.0
4    4        45 2020-12-05    117       148    4060.0
5    5        60 2020-12-06    102       127    3000.0
6    6        60 2020-12-07    110       136    3740.0
7    7       450 2020-12-08    104       134    2533.0
8    8        30 2020-12-09    109       133    1951.0
9    9        60 2020-12-10     98       124    2690.0
10  10        60 2020-12-11    103       147    3293.0
11  11        60 2020-12-12    100       120    2507.0
12  12        60 2020-12-12    100       120    2507.0
13  13        60 2020-12-13    106       128    3453.0
14  14        60 2020-12-14    104       132    3793.0
15  15        60 2020-12-15     98       123    2750.0
16  16        60 2020-12-16     98       120    2152.0
17  17        60 2020-12-17    100       120    3000.0
18  18        45 2020-12-18     90       112       0.0
19  19        60 2020-12-19    103       123    3230.0
20  20        45 2020-12-20     97       125    2430.0
21  21        60 2020-12-21    108       131    3642.0
23  23        60 2020-12-23    130       101    3000.0
24  24        45 2020-12-24    105       132    2460.0
25  25        60 2020-12-25    102       126    3345.0
27  27        60 2020-12-27     92       118    2410.0
28  28        60 2020-12-28    103       132       0.0
29  29        60 2020-12-29    100       132    2800.0
30  30        60 2020-12-30    102       129    3803.0
31  31        60 2020-12-31     92       115    2430.0